server:
  port: 8900

zuul:
  ignored-patterns: /**/user/goods
  sensitive-headers: Cookie, Set-Cookie
  ignored-headers: g1
  routes:
    order:
      path: /order/**
      serviceId: mst-order-service
      stripPrefix: false
    goods:
      path: /goods/**
      serviceId: mst-goods-service
      stripPrefix: false
    user:
      path: /user/**
      serviceId: mst-user-service
      stripPrefix: false
  strip-prefix: true
  prefix: /api

