server:
  port: 8900

zuul:
  sensitive-headers: Cookie, Set-Cookie
  routes:
    order:
      path: /order/**
      serviceId: mst-order-service
      stripPrefix: false
    goods:
      path: /goods/**
      serviceId: mst-goods-service
      stripPrefix: false
    user:
      path: /user/**
      serviceId: mst-user-service
      stripPrefix: false
  semaphore:
      max-semaphores: 500
  ribbon-isolation-strategy: semaphore